---
title: "TestModelBuild"
author: "Brett Taylor"
date: "January 10, 2016"
output: pdf_document
---
#Build Models
```{r buildModel1,warning=FALSE,message=FALSE}
library(RJSONIO)
library(ggplot2)
library(data.table)
source("runModel.R")
source("buildModel.R")
source("goodTuring.R")
curseStops  <- names(fromJSON("./data/google_twunter_lol.json"))



blogsTermMap <- buildTermMap("./data/en_US.blogs.valid.txt",keepApostrophe=TRUE)
twitterTermMap<- buildTermMap("./data/en_US.twitter.valid.txt",keepApostrophe=TRUE)
newsTermMap<- buildTermMap("./data/en_US.news.valid.txt",keepApostrophe=TRUE)


```



##Mappings 

```{r ngramCloud,warning=FALSE ,echo=FALSE,message=FALSE}
options(mc.cores=1)

   library(wordcloud) 
library(knitr)
map <- c(twitterTermMap,blogsTermMap,newsTermMap)
tdmap1  <- buildUnigramMap(map)
tdmap2  <- buildBigramMap(map)
tdmap3 <- buildTrigramMap(map)
tdmap4 <- buildQuadgramMap(map)

ngram.d1 <- as.data.table(buildFrequencyDataSet(tdmap1))
ngram.d2 <- as.data.table(buildFrequencyDataSet(tdmap2))
ngram.d3 <- as.data.table(buildFrequencyDataSet(tdmap3))
ngram.d4 <- as.data.table(buildFrequencyDataSet(tdmap4))



nfreq.uni <- calc.nfreq(ngram.d1,type="uni")
nfreq.bi  <- calc.nfreq(ngram.d2,type="bi")
nfreq.tri <- calc.nfreq(ngram.d3,type="tri")
nfreq.quad <- calc.nfreq(ngram.d4,type="quad")
nfreq <- rbind(nfreq.uni,nfreq.bi,nfreq.tri,nfreq.quad)
nfreq$type <- factor(nfreq$type,levels=c("uni","bi","tri","quad"),
                     labels = c("unigram","bigram","trigram","quadgram"),
                     ordered = TRUE)

#inspect(tdmap)
#object.size(tdmap)


pal <- brewer.pal(6,"Dark2")
pal <- pal[-(1)]

```


```{r nfreqGraph , warning=FALSE ,echo=FALSE,message=FALSE}

p <- ggplot(nfreq,aes(x=log10(freq),y=log10(n_r),color=type))+
        geom_point()+ 
        theme_bw()+

        facet_grid(type~.,as.table = TRUE)
p
```

```{r}

nfreq.uni$gt <- computeGoodTuring(nfreq.uni,FALSE)
freq.uni<-left_join(ngram.d1,nfreq.uni,c("freq"="freq"))
nfreq.bi$gt <- computeGoodTuring(nfreq.bi,FALSE)
freq.bi<-left_join(ngram.d2,nfreq.bi,c("freq"="freq"))

nfreq.tri$gt <- computeGoodTuring(nfreq.tri,FALSE)
freq.tri<-left_join(ngram.d3,nfreq.tri,c("freq"="freq"))

nfreq.quad$gt <- computeGoodTuring(nfreq.quad,FALSE)
freq.quad<-left_join(ngram.d4,nfreq.quad,c("freq"="freq"))

nfreq <- rbind(nfreq.uni,nfreq.bi,nfreq.tri,nfreq.quad)

nfreq$type <- factor(nfreq$type,levels=c("uni","bi","tri","quad"),
                     labels = c("unigram","bigram","trigram","quadgram"),
                     ordered = TRUE)
p <- ggplot(nfreq,aes(x=log10(freq),y=log10(gt),color=type))+
        geom_point()+ 
        theme_bw()+
        facet_grid(type~.,as.table = TRUE)
print(p)
```

\newpage
##Unigram


```{r, echo=FALSE,fig.cap="Top 20 Unigrams"}
ngram.d1$word <- reorder(ngram.d1$word,ngram.d1$freq,rev)
ggplot( head(ngram.d1,20), aes( x = log10(freq), y = word ,size = log(freq), color=log(freq))) + 
        geom_point(  ) + 
         geom_smooth(aes(group=1),alpha=.3,fill="lightblue")+
        guides(color=FALSE,size=FALSE)+
        theme_bw() + 
        theme( panel.grid.major.x = element_blank(), 
               panel.grid.minor.x =element_blank(), 
               panel.grid.major.y = element_line( color ="grey60", linetype ="dashed"))
```

```{r warning=FALSE,fig.cap= "Unigram Frequency"}
kable(head(ngram.d1,20),caption = " Unigram Frequency - Top 20")

wordcloud(ngram.d1$word, ngram.d1$freq,scale = c(4,0.4),colors =  pal,max.words = 300)


```

\newpage

##Bigram

```{r, echo=FALSE,fig.cap="Top 20 Bigrams"}
ngram.d2$word <- reorder(ngram.d2$word,ngram.d2$freq,rev)
ggplot( head(ngram.d2,20), aes( x = log10(freq), y = word ,size = log(freq), color=log(freq))) + 
        geom_point(  ) + 
         geom_smooth(aes(group=1),alpha=.3,fill="lightblue")+
        guides(color=FALSE,size=FALSE)+
        theme_bw() + 
        theme( panel.grid.major.x = element_blank(), 
               panel.grid.minor.x =element_blank(), 
               panel.grid.major.y = element_line( color ="grey60", linetype ="dashed"))
```


```{r warning=FALSE,fig.cap= "Bigram Frequency"}
kable(head(ngram.d2,20),caption = " Bigram Frequency - Top 20")

wordcloud(ngram.d2$word, ngram.d2$freq,scale = c(4,0.4),colors =  pal,max.words = 300)


```

\newpage

##Trigram

```{r, echo=FALSE,fig.cap="Top 20 Trigrams"}
ngram.d3$word <- reorder(ngram.d3$word,ngram.d3$freq,rev)
ggplot( head(ngram.d3,20), aes( x = log10(freq), y = word ,size = log(freq), color=log(freq))) + 
        geom_point(  ) + 
         geom_smooth(aes(group=1),alpha=.3,fill="lightblue")+
        guides(color=FALSE,size=FALSE)+
        theme_bw() + 
        theme( panel.grid.major.x = element_blank(), 
               panel.grid.minor.x =element_blank(), 
               panel.grid.major.y = element_line( color ="grey60", linetype ="dashed"))
```


```{r warning=FALSE,fig.cap= "Trigram Frequency"}
kable(head(ngram.d3,20),caption = " Trigram Frequency - Top 20")

wordcloud(ngram.d3$word, ngram.d3$freq,scale = c(4,0.4),colors =  pal,max.words = 300)


```

\newpage

##Quadgram

```{r, echo=FALSE,fig.cap="Top 20 Quadragrams"}
ngram.d4$word <- reorder(ngram.d4$word,ngram.d4$freq,rev)
ggplot( head(ngram.d4,20), aes( x = log10(freq), y = word ,size = log(freq), color=log(freq))) + 
        geom_point(  ) + 
        geom_smooth(aes(group=1),alpha=.3,fill="lightblue")+
        guides(color=FALSE,size=FALSE)+
        theme_bw() + 
        theme( panel.grid.major.x = element_blank(), 
               panel.grid.minor.x =element_blank(), 
               panel.grid.major.y = element_line( color ="grey60", linetype ="dashed"))
```

```{r warning=FALSE,fig.cap= "Quadragram Frequency"}
kable(head(ngram.d4,20),caption = " Quadragram Frequency - Top 20")

wordcloud(ngram.d4$word, ngram.d4$freq,scale = c(4,0.4),colors =  pal,max.words = 300)


```